# Use the official TensorFlow image with Python 3.9
FROM tensorflow/tensorflow:2.16.1

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    libhdf5-dev \
    unzip \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install AWS CLI version 2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

# Ensure AWS CLI is in the PATH
ENV PATH="/usr/local/aws-cli/v2/current/bin:${PATH}"

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the necessary scripts and directories
COPY src/analysis.py /app/src/analysis.py
COPY src/nn_modeling.py /app/src/nn_modeling.py
COPY pipeline.py /app/pipeline.py
COPY models /app/models
COPY config /app/config

# Create the plots directory
RUN mkdir /app/plots

# Set the entry point to run the pipeline script
ENTRYPOINT ["python", "pipeline.py"]